### ISSUE TITLE
1.1.0 deploy is broken

### ISSUE THREAD

**Issue by rockymeza** [arabold/serverless-sentry-lib#10]
Hi!

I just ran into an issue this morning where trying to deploy code was breaking because of the latest version of serverless-sentry-lib.

[package.json:main](https://unpkg.com/serverless-sentry-lib@1.1.0/package.json) references an index.js file.

However [that file doesn't exist](https://unpkg.com/serverless-sentry-lib@1.1.0/index.js).

The src/ files are still in there though. Maybe the build process wasn't run or something?

Thanks!

**Comment by arabold** [comment]
ARGH! Thanks. 🤦‍♂️

**Comment by arabold** [comment]
Just uploaded 1.1.1 - should fix things. The `index.js` simply moved into the `src/` subfolder and `package.json` wasn't updated. Sorry for that.
