### ISSUE TITLE
Unified Node.js SDK support planed?

### ISSUE THREAD

**Issue by aheissenberger** [arabold/serverless-sentry-lib#12]
https://docs.sentry.io/clients/node/

Deprecated Client raven-node

This SDK has been superseded by a new unified one. The documentation here is preserved for customers using the old client. For new projects have a look at the new client documentation: [Unified Node.js SDK.](https://docs.sentry.io/quickstart?platform=node)

**Comment by arabold** [comment]
New update is coming soon. I've pushed new code already but doing one more change to the API before pushing it to npm.
