### ISSUE TITLE
Allow overrides for Timeout warning/error thresholds

### ISSUE THREAD

**Issue by keanolane** [arabold/serverless-sentry-lib#2]
It would be nice to allow dynamic threshold values for timeout warning and errors.
Even if it's following the AWS best practice, it would be nice to be able to set it differently if needed.

something like that:

```
if (pluginConfig.captureTimeoutWarnings) {
		// We schedule the warning at half the maximum execution time and
		// the error a few milliseconds before the actual timeout happens.
		const warningThreshold = process.env.EXECUTION_TIMEOUT_WARNING_THRESHOLD || timeRemaining / 2;
		const errorThreshold = process.env.EXECUTION_TIMEOUT_ERROR_THRESHOLD || 500;

        timeoutWarning = setTimeout(timeoutWarningFunc, warningThreshold);
		timeoutError = setTimeout(timeoutErrorFunc, Math.max(timeRemaining - errorThreshold, 0));
	}
```

Thanks.

**Comment by arabold** [comment]
Nearly three years later, v2.0.0 has just been released and I still haven't added this functionality. Sorry about that... 😢 

I will look into this for one of the next updates.

**Comment by arabold** [comment]
The latest version 2.2.0 allows you to customize the timeouts via the `withSentry` call options. It does _not_ allow you to set them via global environment variables though, as I want to keep things simple. Setting custom values should be something done rarely and, in my opinion, doesn't warrant support via environment variables or the Serverless plugin itself. 

To set custom timeouts you can do something like this now:
```ts
export const handler = withSentry({ captureTimeouts: { timeRemainingWarning: 3000, timeRemainingError: 500 } }, async (event, context) => {
  console.log("EVENT: \n" + JSON.stringify(event, null, 2));
  return context.logStreamName;
});
```

This code will raise a warning 3 seconds before the Lambda times out and an error 0.5 seconds before.
