### ISSUE TITLE
Sentry - Event filtering

### ISSUE THREAD

**Issue by AlexSun98** [arabold/serverless-sentry-lib#28]
Is there anyway to use event filtering with the lib?

`import * as Sentry from "@sentry/browser";

init({
  beforeSend(event, hint) {
    const error = hint.originalException;
    if (
      error &&
      error.message &&
      error.message.match(/database unavailable/i)
    ) {
      event.fingerprint = ["database-unavailable"];
    }
    return event;
  },
});`

**Comment by arabold** [comment]
Yes, you can pass any custom Sentry options as `sentryOptions` param to the `withSentry` function like this:
```ts
withSentry({
  sentryOptions: { 
    beforeSend: (event, hint) => {
      // ...
    }
  } 
}, handler);
```

Please let me know if this works.

**Comment by SonnyFishback** [comment]
> Yes, you can pass any custom Sentry options as `sentryOptions` param to the `withSentry` function like this:
> 
> ```ts
> withSentry({
>   sentryOptions: { 
>     beforeSend: (event, hint) => {
>       // ...
>     }
>   } 
> }, handler);
> ```
> 
> Please let me know if this works.

Where is this documented? @arabold
