### ISSUE TITLE
Problems with @sentry/node 7

### ISSUE THREAD

**Issue by Gemineye** [arabold/serverless-sentry-lib#36]
Hi, after upgrading to Version 7 we get this errors:

`{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'Info' of undefined",
    "stack": [
        "TypeError: Cannot read property 'Info' of undefined",
        "    at Runtime.handler (/var/task/node_modules/serverless-sentry-lib/dist/index.js:416:43)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}`

It has todo with this line:

` level: SentryLib.Severity.Info,`

Do you have any idea how to fix this?

**Comment by arabold** [comment]
Thanks for the report. I've pushed an update 2.5.0 to GitHub and NPM. I'm unable to test the changes outside of running some local unit tests right now. I would appreciate if you could try and give feedback if possible. Thanks 👍

**Comment by igorescobar** [comment]
Check the migration guide @Gemineye . Severity enum got deprecated.

**Comment by Gemineye** [comment]
@igorescobar The error occured in the lib, not in our code. @arabold We got an error "Cannot find module @sentry/integrations" Maybe you. have to move the dependency from "devDependencies" to "dependencies"?

**Comment by igorescobar** [comment]
Ah, I had to do it myself indeed.

**Comment by arabold** [comment]
`@sentry/integrations` is a peer dependency now, so we the lib can support v7. I need to see if we can get rid of it completely at some point. But simply installing it yourself as your own dependency should fix the problem.

**Comment by Gemineye** [comment]
@arabold your package.json only reference the @sentry/node peer dependency
`  "peerDependencies": {
    "@sentry/node": ">=5"
  },`

**Comment by arabold** [comment]
I'm an idiot. I added the peer dependency to the wrong package.

**Comment by arabold** [comment]
`serverless-sentry-lib` v2.5.1  adds the peer dependency now. Thanks for pointing this out, @Gemineye

**Comment by Gemineye** [comment]
@arabold "^>=5", seems to be incorrect :D

**Comment by igorescobar** [comment]
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^>=5": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by arabold** [comment]
Damn. This is probably related to your NPM or YARN version, as that _should_ work (I'm using npm v8.12.1 right now) , but I'll see what I can do.

**Comment by igorescobar** [comment]
`^>=5` only works with npm >=7 👍 . npm 7 is only bundled by default on node 16 onwards.

**Comment by arabold** [comment]
v2.5.2, please

**Comment by igorescobar** [comment]
- [x] peer depedency `@node/integrations` fixed

**Comment by igorescobar** [comment]
I believe the issue reported here is now fixed 👍 . Will move the other tests on the other project.

**Comment by arabold** [comment]
Thank you for helping and verifying. Much appreciated!
