### ISSUE TITLE
timeRemaining warning/error, memory, shouldn't occur when running lambda locally.

### ISSUE THREAD

**Issue by teebu** [arabold/serverless-sentry-lib#5]
I use node-lambda to run my lambdas `locally`. they don't have `lambdaContext.getRemainingTimeInMillis()`

The module should check if it exists and if not, not throw the warning/error about time and memory.

**Comment by arabold** [comment]
Good point. I've never used `node-lambda` but you're right, it shouldn't give errors if there is no remaining time set.

**Comment by arabold** [comment]
This has been addressed in `node-lambda`: https://github.com/motdotla/node-lambda/pull/179/files
